Clarifications of TOS
WeblateOrg/wllegal pull request #551
Opened 2023-05-03 12:13 UTC by nijel

## Proposed changes

- remove "own" from name, to avoid impression we require a real name
- remove most of Personal Data in TOS, it provided broader consent than Privacy Policy and that is not really needed
- clarify that payment processors get the data only upon purchase

## Checklist

- [ ] Lint and unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added documentation to describe my feature.
- [ ] I have squashed my commits into logic units.
- [ ] I have described the changes in the commit messages.

## Other information

2023-05-03 12:33 UTC, orangesunny requested changes
incorporationg the comments should be enough

2023-05-03 12:33 UTC, orangesunny commented on wllegal/templates/legal/documents/tos.html
> +<p class="item">{% blocktrans %}The User agrees to use of name and e-mail as authorship in the VCS commits. The User understands that this grant is non revocable due to nature of the VCS.{% endblockt
...non-revocable due to the nature...

2023-05-03 12:33 UTC, orangesunny commented on wllegal/templates/legal/documents/tos.html
> +<p class="item">{% blocktrans %}Within the meaning of <a href="{{ url }}">Article 7</a> of the GDPR the User hereby gives consent to the collecting, storage and processing of the Personal Data accord
...gives consent to collecting, storage, and processing...

2023-05-05 12:03 UTC, orangesunny requested changes
just use the semicolon from the only comment and we are goot to go

2023-05-10 15:40 UTC, phw commented on wllegal/templates/legal/documents/privacy.html
> +<h2>{% blocktrans %}Disclossure of to the Personal Data{% endblocktrans %}</h2>
> Disclossure of to the [...]

Typo? "of" or "to"?

2023-05-12 07:08 UTC, nijel commented on wllegal/templates/legal/documents/privacy.html
> +<h2>{% blocktrans %}Disclossure of to the Personal Data{% endblocktrans %}</h2>
```suggestion
<h2>{% blocktrans %}Disclossure of the Personal Data{% endblocktrans %}</h2>
```

2023-05-12 07:39 UTC, nijel commented on wllegal/templates/legal/documents/tos.html
> +<p class="item">{% blocktrans %}Within the meaning of <a href="{{ url }}">Article 7</a> of the GDPR the User hereby gives consent to collecting, storage, and processing of the Personal Data according
```suggestion
<p class="item">{% blocktrans %}Within the meaning of <a href="{{ url }}">Article 7</a> of the GDPR the User hereby gives consent to collecting, storage, and processing of the Personal Data according to the <a href="{{ privacy_url }}">Privacy Policy</a>.{% endblocktrans %}</p>
```

2023-05-14 17:32 UTC, merged